#PostgreSql
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produtodb
    username: postgres
    password: 1234567

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  flyway:
    locations: classpath:/db/migration
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    enabled: false
    validate-on-migrate: false