#H2 database
server:
  port: 8088
spring:
  datasource:
    driver-class-name: org.h2.Driver

    url: jdbc:h2:mem:testdb;
    username: sa
    password: ''

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  flyway:
    enabled: false