#PostgreSql
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produtodb
    username: postgres
    password: 1234567


  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      show-sql: true

